### ISSUE TITLE
[Feature] Markdown

### ISSUE THREAD

**Issue by Drjacky** [bizarre/notion-embeds#2]
How we could use it in  the Markdown/Readme.MD file?
could you generate the image?

This guy did something similar but the output is not pretty: https://github.com/2016rshah/githubchart-api

**Comment by bizarre** [comment]
Hey, sorry for the late reply here! 

AFAIK V1 might've let you use the embed in GH readme's because it just returned an SVG.
Am dropping support for V1 though since it's about 5 years old and is a pain to try and work with and deploy.

This project is specifically for embeds that are built for use in Notion (and built to look good in Notion), so building them to also support embeds in markdown (via rendering an image or SVG or whatever) is kind of out of scope for this project. 

As an aside I think that the project you linked has much prettier charts than what this project initially offered in V1 (+ theming support which is super cool and something I intend to add here one day!)

Will close this issue for now, potentially will revisit if:
1. there's a super easy way to add this support and the want is there
2. i get bored or something lol
